import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Title } from "../components/background/title";
// import { Sound } from "../components/background/sound";
import { CopyRight } from "../components/background/copyright";
// import { CoolongFan } from "../components/background/cooling_fan";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex justify-center items-center bg-[#3A3A3A]">
          <div className="w-[1053px] h-[652px] gameboy-container1 flex justify-center items-center">
            <div className=" w-[1024px] h-[628px] gameboy-container2 flex flex-col relative justify-center">
              <header className="h-[12%] flex justify-center items-center">
                <Title className="w-2/5 h-full" />
              </header>
              <main className="h-[79%]">
                {/* <Sound /> */}
                {children}
              </main>
              <footer className="h-[9%]">
                <CopyRight />
                {/* <CoolongFan /> */}
              </footer>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
