import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Title } from "./styles/title";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex justify-center items-center bg-[#3A3A3A]">
          <div className="w-[1053px] h-[652px] gameboy-container1 flex justify-center items-center">
            <div className=" w-[1024px] h-[628px] gameboy-container2 flex flex-row relative">
              <Title />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
